### ISSUE TITLE
New 1.1 release

### ISSUE THREAD

**Issue by tmassman** [collective/Products.Doormat#8]
Can we please have a new 1.1 release?

**Comment by tmassman** [comment]
Could someone please give me access on pypi to do the release? @mauritsvanrees or @khink maybe?

Thank you

**Comment by mauritsvanrees** [comment]
Your user id is thomas.massmann, right? Done. Thanks for your changes.

**Comment by tmassman** [comment]
Yes, sorry I forgot to mention that. Thank you.

**Comment by tmassman** [comment]
Version 1.1 released on PyPI.

**Comment by mauritsvanrees** [comment]
Thanks for stepping up!
