### ISSUE TITLE
Implement ${navigation_root_url} and ${portal_url} url replacing in Doormat when using Dexterity?

### ISSUE THREAD

**Issue by idgserpro** [collective/Products.Doormat#9]
What do you think of, [when testing for Link type](https://github.com/collective/Products.Doormat/blob/5b62cff464ee42949cc55ea758ec4b4ed05f29da/Products/Doormat/browser/views.py#L91), search for the [placeholders](http://docs.plone.org/external/plone.app.contenttypes/docs/README.html#differences-to-products-atcontenttypes) **${navigation_root_url}** and **${portal_url}**, and replace them with

```python
portal_state = self.context.restrictedTraverse('@@plone_portal_state')                                                                       
navigation_root_url = portal_state.navigation_root_url()                
portal_url = portal_state.portal_url()
```

? Since now this is an official documented feature of Dexterity...

@khink @mauritsvanrees FYI

**Comment by mauritsvanrees** [comment]
I did not know about the placeholders. Ah, it seems we could call `replace_link_variables_by_paths` in the dexterity case, like `indexers.py` in `plone.app.contenttypes` does.

**Comment by idgserpro** [comment]
Should we copy the function and add it do Doormat so Archetypes and Dexterity would benefit from it?

**Comment by mauritsvanrees** [comment]
I think if you try to enter the placeholder in Archetypes, you will get a validation error because it is not recognised as a url. So that won't work.
But I may be wrong, so you can try.

**Comment by idgserpro** [comment]
The idea is to just call this function [here if dexterity](https://github.com/collective/Products.Doormat/blob/5b62cff464ee42949cc55ea758ec4b4ed05f29da/Products/Doormat/browser/views.py#L94) and here if [archetypes](https://github.com/collective/Products.Doormat/blob/5b62cff464ee42949cc55ea758ec4b4ed05f29da/Products/Doormat/browser/views.py#L97).

The problem I see is: the way we have now, the [url](https://github.com/collective/Products.Doormat/blob/5b62cff464ee42949cc55ea758ec4b4ed05f29da/Products/Doormat/browser/views.py#L180) is an `instancemethod` because we have

**url = item.getRemoteUrl**

Why it's not

**url = [item.remote_url](https://github.com/plone/Products.ATContentTypes/blob/c094c822e53f08db433a7a7c9100b0fee8f651a2/Products/ATContentTypes/content/link.py#L64)**

or

**url = [item.getRemoteUrl()](https://github.com/plone/Products.ATContentTypes/blob/c094c822e53f08db433a7a7c9100b0fee8f651a2/Products/ATContentTypes/content/link.py#L75)**

? Is it because the template render the method?

**Comment by mauritsvanrees** [comment]
It probably works because the template uses a `tal` expression to render the url, which will call it if it is a method. Other lines do call for example `item.absolute_url()` so I would say it is fine to call these functions in our python code.

For ATContentTypes: please check if it is even possible to save `${portal_url}` as url.

**Comment by idgserpro** [comment]
Indeed, it doesn't work with Archetypes.

Archetypes, Plone 4.3.9:

![selecao_180](https://cloud.githubusercontent.com/assets/8203476/16466444/9026b7a2-3e19-11e6-8c62-28b702d665a8.png)

![selecao_179](https://cloud.githubusercontent.com/assets/8203476/16466452/993b37a0-3e19-11e6-9146-60bcc4e0b750.png)

Dexterity, Plone 4.3.9:

![selecao_178](https://cloud.githubusercontent.com/assets/8203476/16466462/a4bf7c30-3e19-11e6-959b-2ac27eee0eb2.png)

![selecao_177](https://cloud.githubusercontent.com/assets/8203476/16466467/aa6db00c-3e19-11e6-8d36-af749251b0ce.png)

Nice find about `replace_link_variables_by_paths` @mauritsvanrees! I think the correct approach is to just call this function after `item.remoteUrl` (and a test).

**Comment by idgserpro** [comment]
Maybe we can do this in a PR, are you interested? @khink @mauritsvanrees

**Comment by mauritsvanrees** [comment]
sure, go ahead

**Comment by idgserpro** [comment]
@mauritsvanrees PR made in https://github.com/collective/Products.Doormat/pull/10 :)

**Comment by idgserpro** [comment]
@mauritsvanrees @hvelarde if it's possible to anyone familiar with the package to take a look into our PR? We would gladly appreciate!
